#!/bin/sh

LEVEL=$(cat /sys/class/power_supply/BAT0/capacity);

# [ $LEVEL -gt 90 ] &&  echo "" && exit 0 
# [ $LEVEL -gt 75 ] &&  echo "" && exit 0 
# [ $LEVEL -gt 50 ] &&  echo "" && exit 0 
# [ $LEVEL -gt 25 ] &&  echo "" && exit 0 
# echo ""
[ $LEVEL -gt 95 ] &&  echo "" && exit 0 
[ $LEVEL -gt 90 ] &&  echo "" && exit 0 
[ $LEVEL -gt 80 ] &&  echo "" && exit 0 
[ $LEVEL -gt 70 ] &&  echo "" && exit 0 
[ $LEVEL -gt 60 ] &&  echo "" && exit 0 
[ $LEVEL -gt 50 ] &&  echo "" && exit 0 
[ $LEVEL -gt 40 ] &&  echo "" && exit 0 
[ $LEVEL -gt 30 ] &&  echo "" && exit 0 
[ $LEVEL -gt 20 ] &&  echo "" && exit 0 
[ $LEVEL -gt 10 ] &&  echo "" && exit 0 
echo ""
