#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x conky > /dev/null || (conky &)
# pgrep -x stalonetray > /dev/null || ($HOME/.scripts/bsp-tray )

FIRST_MON="      "
SECOND_MON="ﭮ   "


if [ -z "$(xrandr --listactivemonitors | grep HDMI2)" ]; then
	bspc monitor eDP1 -d $FIRST_MON
 	bspc monitor HDMI1 -d $SECOND_MON  && ((ps aux | grep "[0-9] polybar mybar2") || polybar mybar2 &)
	ps aux | grep "[0-9] polybar mybar$" > /dev/null || (polybar mybar &)
	$HOME/.screenlayout/default.sh
else 
	bspc monitor HDMI2 -d $FIRST_MON
	bspc monitor eDP1 -d $SECOND_MON
	ps aux | grep "[0-9] polybar mybar3" > /dev/null || (polybar mybar3 &)
	ps aux | grep "[0-9] polybar mybar$" > /dev/null || (polybar mybar &)
	$HOME/.screenlayout/big_monitor.sh
fi

bspc config border_width 2
BW=0
bspc config window_gap -$BW
for side in top right bottom left ; do
	bspc config ${side}_padding $BW
done

bspc config top_padding 18 

for side in top right bottom left ; do
	bspc config ${side}_monocle_padding 0
done

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle      true
bspc config focused_border_color  \#D184E3
	bspc config normal_border_color  \#272737

	bspc config automatic_scheme longest_side
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a *:*:nmtui state=floating
bspc rule -a *:*:pmixer state=floating
bspc rule -a *:*:stalonetray state=floating

bsp-layout set tall 1 &
